description: >
  Build the Project-X artifact.

executor: << parameters.executor >>

parameters:
  app-root:
    type: string
    description: 'Set the application root path.'
    default: '~/project'
  executor:
    type: executor
    description: 'Set the PHP application executor.'
    default: php/default
  composer-version:
    type: string
    default: ''
    description: 'Set a particular composer version to use.'
  php-before-install:
    type: steps
    description: 'Steps to executed before PHP packages are installed.'
    default: []
  php-after-install:
    type: steps
    description: 'Steps to executed after PHP packages are installed.'
    default: []
  command-args:
    type: string
    description: 'Set the project-x build command arguments.'
    default: ''

steps:
  - checkout
  - install-php-packages:
      after: << parameters.php-after-install >>
      before: << parameters.php-before-install >>
      composer-version: << parameters.composer-version >>
  - run:
      name: Build PHP artifact
      command: vendor/bin/px artifact:build --no-interaction << parameters.command-args >>
  - persist_to_workspace:
      root: << parameters.app-root >>
      paths:
        - build
